# Only run the pipeline for merge-requests
workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

# Use our custom Docker image with Ubuntu 22.04, MuJoCo and CoppeliaSim
image: collaborating.tuhh.de:5005/ckv0173/scilab-rl/scilabrl

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

stages:
    - prepare
    - smoke_test
    - performance_test

set-up-project:
    stage: prepare
    # cache the pip cache for every branch
    cache:
      key: $CI_COMMIT_REF_SLUG
      paths:
        - .cache/pip
    script:
        - pip install -r requirements.txt
        - export PYTHONPATH=$PYTHONPATH:$(pwd)
        - export MUJOCO_PY_MUJOCO_PATH=/mujoco210
        - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$MUJOCO_PY_MUJOCO_PATH/bin
        - pip install mujoco-py
        - export COPPELIASIM_ROOT=/CoppeliaSim_Edu_V4_1_0_Ubuntu20_04
        - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$COPPELIASIM_ROOT
        - export QT_QPA_PLATFORM_PLUGIN_PATH=$COPPELIASIM_ROOT
        - pip install git+https://github.com/stepjam/PyRep.git git+https://github.com/stepjam/RLBench.git pyquaternion natsort
        - python3 experiment/train.py wandb=0 n_epochs=1
        - xvfb-run -a python3 experiment/train.py wandb=0 n_epochs=1 env=reach_target-state-v0

run-smoke-test:
    stage: smoke_test
    script:
      - exit 0

run-performance-test:
    stage: performance_test
    script:
      - exit 0
