workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

stages:
    - prepare
    - smoke_test
    - performance_test

prepare-job:
    stage: prepare
    script:
        - echo "Didn't crash yet"

run-smoke-test:
    stage: smoke_test
    script:
      - exit 0

run-performance-test:
    stage: performance_test
    script:
      - ls