# @package _global_
# Changes specified in this config should be interpreted as relative to the _global_ package.
defaults:
  # access algorithm config group to get the default parameters of her
  - override /algorithm: sac

# overwrite parameters of main.yaml
env: 'FetchPush-v1'

# use HER
using_her: true
algorithm:
  buffer_size: 1000000
  batch_size: 2048
  learning_rate: 0.001
  tau: 0.05
  policy_kwargs:
    n_critics: 2
    net_arch:
      - 400
      - 300
    use_sde: false
  replay_buffer_kwargs:
    n_sampled_goal: 4
    goal_selection_strategy: 'future'
    online_sampling: True

performance_testing_conditions:
  # In 2 out of 3 tests, the test/success rate should be at least 0.9 after 10000 steps.

  total_runs: 3 # How many runs in total:

  succ_runs: 2 # This number of runs should meet the conditions:

  eval_columns: test/success_rate # This is what we evaluate to determine success. Will use this to override the \'early_stop_data_column\' parameter of main.yaml

  eval_value: 0.9 # This is the value we determine for success. Will use this to determine and override the \'early_stop_threshold\' parameter of main.yaml

  max_steps: 10000 # This is the time limit for checking the success. Will use this and the \'eval_after_n_steps\' parameter of main.yaml to determine the n_epochs parameter in main.yaml.

hydra:
  sweeper:
    n_jobs: 3
    _target_: hydra_plugins.hydra_custom_optuna_sweeper.performance_testing_sweeper.PerformanceTestingSweeper
    study_name: sac_her_FetchPush-test
