# @package _global_
# Changes specified in this config should be interpreted as relative to the _global_ package.
defaults:
  # access algorithm config group to get the default parameters of sac
  - override /algorithm: ddpg

# overwrite default parameters.
env: 'FetchPush-v1'

# use HER
using_her: true
algorithm:
  buffer_size: 1000000
  batch_size: 2048
  policy_kwargs:
    n_critics: 1
    # net_arch:
    #   - 400
    #   - 300
  replay_buffer_kwargs:
    n_sampled_goal: 4
    goal_selection_strategy: 'future'
    online_sampling: True

hydra:
  sweeper:
    study_name: ddpg_her_FetchPush
    max_trials: 32
    n_jobs: 8
    direction: maximize
    max_duration_minutes: 600
    min_trials_per_param: 2
    max_trials_per_param: 3
    search_space:
      +algorithm.learning_rate:
        type: float
        low: 1e-4
        high: 1e-2
        log: true
      ++algorithm.gamma:
        type: float
        low: 0.9
        high: 0.99
        log: true
      ++algorithm.policy_kwargs.n_critics:
        type: int
        low: 1
        high: 2
      # ++algorithm.policy_kwargs.net_arch:
      #   type: categorical
      #   choices:
      #   - [256, 256]
      #   - [400, 300]
      #   - [512, 512]

