# @package _global_
# Changes specified in this config should be interpreted as relative to the _global_ package.

algorithm:
  name: 'cleanppo'
  learning_rate: 0.0003
  num_steps: 2048
  num_envs: 1
  anneal_lr: True
  gamma: 0.99
  gae_lambda: 0.95
  num_minibatches: 32
  update_epochs: 10
  clip_coef: 0.2
  norm_adv: True
  clip_vloss: True
  ent_coef: 0.0
  vf_coef: 0.5
  max_grad_norm: 0.5
  target_kl: null
