# @package _global_
# Changes specified in this config should be interpreted as relative to the _global_ package.

algorithm:
  name: 'mysac'
  q_lr: 0.001
  policy_lr: 0.0003
  autotune: True
  alpha: 0.2
  buffer_size: 1_000_000
  learning_starts: 5_000
  batch_size: 256
  gamma: 0.99
  policy_frequency: 2
  target_network_frequency: 1
  tau: 0.005
