# @package _global_

hydra:
  # sweeper, sampler and search_space for hyperparameter optimization. Hyperparameter optimization can be started with --multirun as commandline parameter when executing train.py
  sweeper:
    sampler:
      _target_: optuna.samplers.BaseSampler
      seed: ${now:%f}
      n_startup_trials: 1
      n_ei_candidates: 1
      warn_independent_sampling: true
    _target_: hydra_plugins.hydra_custom_optuna_sweeper.custom_optuna_sweeper.CustomOptunaSweeper
    direction: maximize
    study_name: smoke_test
    n_trials: 1
    n_jobs: 1
    max_trials: 1
    max_duration_minutes: 7
    min_trials_per_param: 1
    max_trials_per_param: 1
