# @package _global_
# Changes specified in this config should be interpreted as relative to the _global_ package.
defaults:
  - override /algorithm: ppo

env: 'MoonlanderWorld-v0'
algorithm:
  gamma: 0.99
  gae_lambda: 0.95
  batch_size: 64
hydra:
  sweeper:
    study_name: ppo_moonlander
    max_trials: 100
    n_jobs: 10
    direction: maximize
    max_duration_minutes: 600
    min_trials_per_param: 1
    max_trials_per_param: 3
    search_space:
      ++algorithm.learning_rate:
        type: float
        low: 0.00005
        high: 0.005
        log: true
