# @package _global_
# Changes specified in this config should be interpreted as relative to the _global_ package.
defaults:
  - override /algorithm: sac

n_epochs: 150

env: 'Blocks-o1-gripper_none-v1'

using_her: true
algorithm:
  buffer_size: 1000000
  learning_rate: 0.001
  policy_kwargs:
    net_arch:
      - 256
      - 256
      - 256
  replay_buffer_kwargs:
    n_sampled_goal: 4
    goal_selection_strategy: 'future'
    online_sampling: True

hydra:
  sweeper:
    study_name: sac_her_Blocks_o1_none
    max_trials: 32
    n_jobs: 8
    direction: maximize
    max_duration_minutes: 36000
    min_trials_per_param: 2
    max_trials_per_param: 3
    search_space:
      ++algorithm.gamma:
        type: float
        low: 0.9
        high: 0.99
        log: true
      ++algorithm.tau:
        type: float
        low: 0.005
        high: 0.1
        log: true
      ++algorithm.policy_kwargs.n_critics:
        type: int
        low: 1
        high: 4
      ++algorithm.policy_kwargs.use_sde:
        type: categorical
        choices:
        - True
        - False
      ++algorithm.batch_size:
        type: categorical
        choices:
        - 256
        - 512
        - 1024
        - 2048
      ++algorithm.ent_coef:
        type: categorical
        choices:
        - 'auto'
        - 0.01
        - 0.1
        - 0.2
